# Generated by Django 4.2.5 on 2024-10-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kategori', models.CharField(max_length=255)),
                ('harga', models.IntegerField()),
                ('toko', models.CharField(max_length=255)),
                ('alamat', models.TextField()),
                ('kontak', models.CharField(max_length=255)),
                ('gambar', models.ImageField(upload_to='')),
            ],
        ),
    ]
