# Generated by Django 5.1.2 on 2024-10-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="ikon_botak/foto_ikon.jpg",
                null=True,
                upload_to="profile_pictures/",
            ),
        ),
    ]
