# Generated by Django 5.1 on 2024-10-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gambar',
            field=models.ImageField(upload_to='static/image/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/ikon_botak/foto_ikon.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
