# Generated by Django 5.1.2 on 2024-10-27 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='commenter_name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
        migrations.AddField(
            model_name='forum',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main.forum'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gambar',
            field=models.ImageField(upload_to='static/image/'),
        ),
    ]
