# Generated by Django 5.1.2 on 2024-10-23 19:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_review_unique_together_remove_forum_parent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="admin",
        ),
    ]
