# Generated by Django 4.2.5 on 2024-10-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_product_admin'),
        ('main', '0004_userprofile'),
    ]

    operations = [
    ]
