# Generated by Django 5.1 on 2024-10-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_cart_product_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gambar',
            field=models.TextField(),
        ),
    ]
