# Generated by Django 5.1 on 2024-10-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_product_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gambar',
            field=models.URLField(),
        ),
    ]
