# Generated by Django 4.2.5 on 2024-10-24 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_product_gambar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='gambar',
            field=models.ImageField(upload_to=''),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
