# Generated by Django 5.1 on 2024-10-24 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_product_gambar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gambar',
            field=models.ImageField(upload_to=''),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
