# Generated by Django 4.2.5 on 2024-10-24 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_review_unique_together'),
        ('main', '0012_alter_product_gambar'),
    ]

    operations = [
    ]
