# Generated by Django 5.1.2 on 2024-10-25 16:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_alter_product_gambar"),
        ("main", "0013_merge_20241024_1952"),
    ]

    operations = []
