# Generated by Django 5.1.2 on 2024-10-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_create_forum_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='commenter_name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
