# Generated by Django 4.2.5 on 2024-10-26 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_product_gambar'),
        ('main', '0013_merge_20241024_1952'),
    ]

    operations = [
    ]
