# Generated by Django 5.1.2 on 2024-10-25 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_admin_alter_product_id_forum_review 2'),
        ('main', '0003_alter_review_unique_together_remove_forum_parent_and_more 2'),
        ('main', '0004_remove_product_admin 2'),
        ('main', '0004_userprofile 2'),
        ('main', '0005_merge_0004_remove_product_admin_0004_userprofile 2'),
        ('main', '0006_remove_cart_product_cartitem 2'),
        ('main', '0007_alter_product_gambar 2'),
        ('main', '0008_alter_product_gambar 2'),
        ('main', '0009_alter_product_gambar 2'),
        ('main', '0010_cart_product_alter_product_gambar_delete_cartitem 2'),
        ('main', '0011_alter_review_unique_together 2'),
        ('main', '0011_cart_email_cart_name_cart_phone_number_cart_time 2'),
        ('main', '0012_alter_product_gambar 2'),
        ('main', '0013_alter_product_gambar 2'),
        ('main', '0013_alter_product_gambar'),
        ('main', '0013_merge_20241024_1952 2'),
        ('main', '0013_merge_20241024_1952'),
    ]

    operations = [
    ]
