# Generated by Django 5.1.2 on 2024-10-26 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_forum_commenter_name'),
        ('main', '0015_userprofile_alamat_userprofile_bio_and_more'),
    ]

    operations = [
    ]
